cloud:
  aws:
    credentials:
      access-key: AKIAZJOMCYFCOL4GHFFE
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: nachiketbucket


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB